name: Kindlefy (Daily Tests)

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Kindlefy Daily Tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Packages
        run: npm install

      - name: Run Kindlefy Integration and Unit tests
        run: npm run test:ci
